# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       pulseaudio-settings-n950

# >> macros
# << macros

Summary:    PulseAudio settings for N950 and N9
Version:    4.0.5
Release:    1
Group:      System/Libraries
License:    GPLv2
BuildArch:  noarch
URL:        https://github.com/nemomobile/pulseaudio-settings-n950-n9
Source0:    pulseaudio-settings-n950-n9-%{version}.tar.gz
Source100:  pulseaudio-settings-n950.yaml
Requires:   pulseaudio >= 4.0
Requires:   pulseaudio-modules-nemo-voice >= 4.0.4
Requires:   pulseaudio-modules-nemo-music >= 4.0.4
Requires:   pulseaudio-modules-nemo-record >= 4.0.4
Requires:   pulseaudio-modules-nemo-parameters >= 4.0.4
Requires:   pulseaudio-modules-nemo-stream-restore >= 4.0.4
Requires:   pulseaudio-modules-nemo-mainvolume >= 4.0.4
Requires:   pulseaudio-module-cmtspeech-n9xx >= 4.0.3
Requires:   pulseaudio-policy-enforcement
Provides:   pulseaudio-settings
Obsoletes:   pulseaudio-modules-nokia-common-bin
Obsoletes:   pulseaudio-modules-nokia-algorithms-bin
Obsoletes:   pulseaudio-modules-nokia-audiots-bin
Obsoletes:   pulseaudio-modules-nokia-parameters-bin

%description
PulseAudio, previously known as Polypaudio, is a sound server for POSIX and WIN32 systems. It is a drop in replacement for the ESD sound server with much better latency, mixing/re-sampling quality and overall architecture. This package includes device specific settings for PulseAudio.


%package debug
Summary:    PulseAudio debugging support
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}

%description debug
This package enables logging in PulseAudio and Policy components (stored in /var/log) and has dependencies to all relevant -dbg packages.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre

# >> install post
install -d %{buildroot}/%{_sysconfdir}/pulse
install -d %{buildroot}/%{_sysconfdir}/sysconfig
install -d %{buildroot}/%{_sysconfdir}/debug.d
install -d %{buildroot}/%{_sbindir}
install -d %{buildroot}/%{_datadir}
install -d %{buildroot}/%{_localstatedir}
install -m 644 etc/pulse/*.{pa,table} %{buildroot}/%{_sysconfdir}/pulse/
install -m 644 etc/sysconfig/pulseaudio %{buildroot}/%{_sysconfdir}/sysconfig/
ln -s %{_sysconfdir}/pulse/arm_nokia_rm_680_board.pa %{buildroot}/%{_sysconfdir}/pulse/arm_nokia_rm_696_board.pa
install -m 644 etc/debug.d/* %{buildroot}/%{_sysconfdir}/debug.d/
cp -a usr/share/* %{buildroot}/%{_datadir}/
cp -a var/* %{buildroot}/%{_localstatedir}/
# << install post

%files
%defattr(-,root,root,-)
%config %{_sysconfdir}/pulse/arm_nokia_rm_680_board.pa
%config %{_sysconfdir}/pulse/arm_nokia_rm_696_board.pa
%config %{_sysconfdir}/pulse/*.table
%config %{_sysconfdir}/sysconfig/pulseaudio
%{_datadir}/pulseaudio/alsa-mixer/profile-sets/*.conf
%{_datadir}/pulseaudio/alsa-mixer/paths/*.conf
%{_localstatedir}/lib/*
# >> files
# << files

%files debug
%defattr(-,root,root,-)
%config %{_sysconfdir}/debug.d/*
# >> files debug
# << files debug
